name: License Compliance & CLA Gate

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  license-check:
    # Run on PR events or CLA-related comments
    if: |
      github.event_name == 'pull_request_target' || 
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA'))
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Payload
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Enabled Repos: ${{ vars.ENABLED_REPOS }}"
          echo "Excluded Repos: ${{ vars.EXCLUDED_REPOS }}"
          
      - name: Check if repository is enabled or excluded
        id: repo_filter
        shell: python
        env:
          ENABLED_REPOS: ${{ vars.ENABLED_REPOS || '[]' }}
          EXCLUDED_REPOS: ${{ vars.EXCLUDED_REPOS || '[]' }}
          CURRENT_REPO: ${{ github.repository }}
        run: |
          import os
          import json

          try:
              # Load repository lists from environment variables
              enabled_repos = json.loads(os.environ['ENABLED_REPOS'])
              excluded_repos = json.loads(os.environ['EXCLUDED_REPOS'])
              current_repo = os.environ['CURRENT_REPO']

              # Check enabled repos first if specified
              if enabled_repos:
                  if current_repo not in enabled_repos:
                      print(f"⚠️ Skipping {current_repo} - not in enabled list")
                      print(f"Enabled repos: {', '.join(enabled_repos)}")
                      with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                          fh.write('should_run=false')
                      exit(0)

              # Then check excluded repos
              if current_repo in excluded_repos:
                  print(f"⚠️ Skipping {current_repo} - in excluded list")
                  print(f"Excluded repos: {', '.join(excluded_repos)}")
                  with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                      fh.write('should_run=false')
                  exit(0)

              # Repository is allowed to run
              print(f"✅ Running checks for {current_repo}")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                  fh.write('should_run=true')

          except json.JSONDecodeError as e:
              print(f"❌ Error parsing repository lists: {e}")
              print(f"ENABLED_REPOS: {os.environ['ENABLED_REPOS']}")
              print(f"EXCLUDED_REPOS: {os.environ['EXCLUDED_REPOS']}")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                  fh.write('should_run=false')
              exit(1)

      - name: Get PR SHA
        id: pr_sha
        if: steps.repo_filter.outputs.should_run == 'true'
        shell: python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
          EVENT_PATH: ${{ github.event_path }}
          REPOSITORY: ${{ github.repository }}
        run: |
          import os
          import json
          from github import Github

          try:
              event_name = os.environ['EVENT_NAME']
              
              # For pull_request_target events, get SHA directly from event payload
              if event_name == 'pull_request_target':
                  with open(os.environ['EVENT_PATH']) as f:
                      event_data = json.load(f)
                      sha = event_data['pull_request']['head']['sha']
                      print(f"✅ Got SHA from pull_request_target event: {sha}")
              
              # For issue_comment events, need to fetch PR details
              else:
                  g = Github(os.environ['GITHUB_TOKEN'])
                  repo = g.get_repo(os.environ['REPOSITORY'])
                  with open(os.environ['EVENT_PATH']) as f:
                      event_data = json.load(f)
                      pr_number = event_data['issue']['number']
                  
                  pr = repo.get_pull(pr_number)
                  sha = pr.head.sha
                  print(f"✅ Got SHA from PR #{pr_number}: {sha}")

              # Write SHA to output
              with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                  fh.write(f'sha={sha}')

          except Exception as e:
              print(f"❌ Error getting PR SHA: {e}")
              exit(1)

      - name: Checkout PR Head
        if: steps.repo_filter.outputs.should_run == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr_sha.outputs.sha }}
          fetch-depth: 0

      - name: Fuzzy License Validation
        if: steps.repo_filter.outputs.should_run == 'true'
        id: license_check
        uses: ./.github/actions/check-license

      - name: Enforce CLA
        if: steps.license_check.outputs.license_status == 'non-permissive' && steps.repo_filter.outputs.should_run == 'true'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/${{ github.repository }}/cla.json'
          path-to-document: 'https://${{ github.repository_owner }}.github.io/cla-docs/GenericCLA.html'
          branch: 'main'
          allowlist: 'org-admin,bot*'
          # Optional inputs (uncomment and customize as needed)
          # remote-organization-name: 'your-remote-org'
          # remote-repository-name: 'your-remote-repo'
          # create-file-commit-message: 'Creating file for storing CLA Signatures'
          # signed-commit-message: '$contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          # custom-notsigned-prcomment: 'Please sign the CLA to contribute.'
          # custom-pr-sign-comment: 'I have read the CLA Document and I hereby sign the CLA'
          # custom-allsigned-prcomment: 'All contributors have signed the CLA.'
          # lock-pullrequest-aftermerge: false
          # use-dco-flag: false
