# File: .github/.github/workflows/reusable-cla-check.yml
# Purpose: Centralized, reusable workflow for performing the CLA check.
# Signatures are read from and committed to a CSV file within this .github repository.

name: Reusable CLA Check (Repo Signatures)

on:

  workflow_call:
    secrets:
      # This PAT is used by cla-assistant/github-action for:
      # 1. PR interactions (comments, labels, statuses) on the TARGET repository.
      # 2. Reading and committing signatures to the CLA.csv file in THIS .github repository.
      # It requires:
      # - Pull requests: R/W, Issues: R/W, Commit statuses: R/W (for all target repos).
      # - Contents: R/W (for THIS .github repository to manage CLA.csv).
      CONTRIBUTOR_ASSISTANT_PAT:
        description: 'PAT for CLA Assistant Lite (PR interaction on target repos AND signature commits to this .github repo).'
        required: true
    inputs:
      # URL or path to the CLA document text.
      # If a path, it's relative to the root of THIS .github repository after checkout.
      cla_document_url:
        description: 'URL or path to the CLA document text.'
        required: false # Made optional, can default
        type: string
        default: 'https://vmware.github.io/cla-docs/GenericCLA.html' # Dynamic default
        # default: 'https://github.com/${{ github.repository_owner }}/.github/blob/main/.github/CONTRIBUTOR_LICENSE_AGREEMENT.md' # Dynamic default
      # Path to the CSV signature file within THIS .github repository.
      signature_file_path:
        description: 'Path to the CSV signature file within this .github repository.'
        required: false
        type: string
        default: 'signatures/CLA.csv' # Default path
      # Branch in THIS .github repository where signatures are stored and committed.
      signature_branch:
        description: 'Branch in this .github repository where signatures are stored and committed.'
        required: false
        type: string
        default: 'main' # Default branch (e.g., main or your .github repo's default)

# Permissions this reusable workflow's GITHUB_TOKEN needs in the context of the CALLER's repository (target repo).
# cla-assistant/github-action primarily uses its own CONTRIBUTOR_ASSISTANT_PAT for its operations.
permissions:
  pull-requests: write # For commenting/labeling on the target PR.
  issues: write        # For commenting on issues on the target PR.
  statuses: write      # For setting commit statuses on the target PR.
  # Contents: write on THIS .github repo is handled by the CONTRIBUTOR_ASSISTANT_PAT PAT,
  # not this workflow's GITHUB_TOKEN.

jobs:
  cla_check:
    runs-on: ubuntu-latest
        # The 'if' condition to run this job is now primarily handled by the CALLER (the stub workflow).
        # Run only for relevant PR actions.
    steps:
      # Checkout THIS .github repository.
      # This makes the signature file (e.g., .github/signatures/CLA.csv) and potentially the
      # CLA document (if stored locally) available to the cla-assistant-lite action.
      - name: Checkout .github repository (for signature file access)
        uses: actions/checkout@v4.1.1
        with:
          # Explicitly checkout THIS .github repository where the workflow runs and signatures are stored.
          repository: ${{ github.repository }} # e.g., YOUR_ORG/.github
          # Checkout the branch where the signature file (CLA.csv) is located and where new signatures will be committed.
          ref: ${{ inputs.signature_branch }}
          # The default GITHUB_TOKEN of this job is sufficient for checking out its own repository.

      - name: CLA Assistant Lite (Signatures in Repo)
        # Use the official cla-assistant/github-action. Pin to a specific version.
        uses: contributor-assistant/github-action@v2.6.1
        env:
          # Provide the dedicated PAT. This PAT needs permissions for:
          # 1. PR interactions (comments, labels, statuses) on the *target repository* (where the PR was opened).
          # 2. Contents Read & Write permissions on *this .github repository* to read/commit CLA.csv.
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTOR_ASSISTANT_PAT }}
        with:
          # Path to the signature CSV file within the checked-out .github repository.
          path-to-signatures: ${{ inputs.signature_file_path }}
          # Path or URL to the CLA document text.
          path-to-document: ${{ inputs.cla_document_url }}
          # Branch in THIS .github repository where new signatures should be committed.
          branch: ${{ inputs.signature_branch }}
          # List of users/bots to ignore for CLA checks.
          allowlist: bot*,dependabot[bot],github-actions[bot],renovate[bot]

          # --- Optional configurations for cla-assistant-lite ---
          # Custom commit message when a new signature is added to CLA.csv.
          # Uses GitHub context variables available to cla-assistant-lite.
          create-file-commit-message: 'chore(CLA): Add signature for @${{ github.event.sender.login }} for PR #${{ github.event.pull_request.number }} on ${{ github.event.repository.full_name }}'
          
          # User to attribute commits to if the action commits signatures.
          # github-actions[bot] is a good default if you want to distinguish these commits.
          # commit-author-name: 'CLA Automation'
          # commit-author-email: 'cla-bot@users.noreply.github.com' # Or a dedicated bot user email

          # Lock PR from non-members until CLA is signed
          # lock-pullrequest-after: true
          # Custom message when CLA is required
          # sigRequiredComment: 'Thanks for your contribution! Please sign our CLA to proceed.'
