name: Org License Report (public repos)

on:
  workflow_dispatch:
    inputs:
      org:
        description: "GitHub organization (login) to scan"
        required: true
      max_concurrency:
        description: "Max concurrent repo tasks (default 16)"
        required: false
        default: "16"
      request_timeout_s:
        description: "Per-request timeout seconds (default 20)"
        required: false
        default: "20"
      api_base_url:
        description: "GitHub API base (use for GH Enterprise)"
        required: false
        default: "https://api.github.com"

  # Optional scheduled run
  schedule:
    - cron: "0 7 * * 1"

permissions:
  contents: read
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central .github repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp rapidfuzz charset-normalizer

      - name: Cache detector index
        uses: actions/cache@v4
        with:
          path: .github/tools/.cache
          # Include catalog, policy, and detector code in the cache key to avoid stale logic
          # key: licenses-cache-${{ hashFiles('data/licenses_all.json', 'data/licenses_all.json.gz', 'data/permissive_names.json', 'scripts/license_detector.py') }}
          key: licenses-cache-${{ hashFiles('data/licenses_all.json', 'data/licenses_all.json.gz', 'data/permissive_names.json', 'scripts/license_detector.py') }}-${{ github.run_id }}


      - name: Run org-wide license scan
        env:
          # Fine-grained PAT as an **Organization secret**
          # Repo permissions: Metadata (Read), Contents (Read)
          GITHUB_TOKEN: ${{ secrets.ORG_LICENSE_REPORT_TOKEN }}
          API_BASE_URL: ${{ inputs.api_base_url }}
          LICENSES_JSON: data/licenses_all.json
          PERMISSIVE_JSON: data/permissive_names.json
          CACHE_DIR: .github/tools/.cache
        run: |
          python scripts/detect_org_repo_licenses.py \
            --org "${{ inputs.org:-vmware }}" \
            --max-concurrency "${{ inputs.max_concurrency:-16 }}" \
            --timeout-s "${{ inputs.request_timeout_s:-20 }}" \
            --output-json "license_report.json" \
            --output-csv "license_report.csv"

      - name: Summarize results
        run: |
          echo "### Org License Report Summary" >> $GITHUB_STEP_SUMMARY
          jq -r '.summary | to_entries[] | "- **\(.key)**: \(.value)"' license_report.json >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### First 20 rows" >> $GITHUB_STEP_SUMMARY
          head -n 21 license_report.csv | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: license-report-${{ inputs.org }}
          path: |
            license_report.json
            license_report.csv
