name: Scan Organization Repos for Licenses

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: 'GitHub Organization Name to scan'
        required: true
        default: ${{ github.event.repository.owner.login }} # Defaults to the organization of the repo where workflow is run
      max_clone_retries:
        description: 'Max retries for git clone operations'
        required: false
        default: '5'
      clone_retry_delay_seconds:
        description: 'Delay between clone retries (seconds)'
        required: false
        default: '10'

jobs:
  license_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
      organization: read # Required for gh repo list to access org repos
      pull-requests: write # To allow cloning private repos using GITHUB_TOKEN
      # If you are scanning private repos, the GITHUB_TOKEN needs appropriate read permissions
      # on those repositories, which is usually handled by the default token's scope
      # when triggered from within the organization.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for licensee)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # licensee requires Node.js

      - name: Install licensee
        run: npm install -g licensee

      - name: Set up GitHub CLI
        run: |
          # gh CLI is usually pre-installed on GitHub Actions runners,
          # but this step ensures it's available and configured.
          echo "GH_TOKEN_FOR_CLI=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          gh auth setup-git

      - name: Scan Organization Repositories
        id: scan
        env:
          ORG_NAME: ${{ github.event.inputs.organization_name }}
          MAX_RETRIES: ${{ github.event.inputs.max_clone_retries }}
          RETRY_DELAY: ${{ github.event.inputs.clone_retry_delay_seconds }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Passed to shell for cloning private repos
        run: |
          set -euo pipefail

          SCAN_RESULTS_FILE="license_scan_results.json"
          TEMP_JSONL_FILE="temp_results.jsonl"
          CLONE_DIR="temp_clones"

          echo "Starting license scan for organization: $ORG_NAME"
          mkdir -p "$CLONE_DIR"

          # Initialize a temporary file for JSON Lines output
          # This is more efficient than building a large JSON array in shell variables
          > "$TEMP_JSONL_FILE"

          # Get all repositories for the organization
          # --limit 9999 ensures we get all of them, as default is often 30-100
          # --json name,url extracts the repo name and clone URL
          echo "Fetching repository list for $ORG_NAME..."
          REPO_LIST_JSON=$(gh repo list "$ORG_NAME" --json name,url --limit 9999 || { echo "Failed to fetch repository list. Check ORG_NAME and GITHUB_TOKEN permissions."; exit 1; })

          # Loop through each repository
          echo "$REPO_LIST_JSON" | jq -c '.[]' | while IFS= read -r repo_json; do
              REPO_NAME=$(echo "$repo_json" | jq -r '.name')
              REPO_URL=$(echo "$repo_json" | jq -r '.url')
              REPO_DIR="$CLONE_DIR/$REPO_NAME"

              echo "--- Processing repository: $REPO_NAME ---"
              DETECTED_LICENSE="Not Detected" # Default if licensee finds nothing or clone fails

              CLONE_SUCCESS=false
              for i in $(seq 1 "$MAX_RETRIES"); do
                  echo "Attempt $i/$MAX_RETRIES to clone $REPO_NAME..."
                  # Use the GITHUB_TOKEN directly in the URL for cloning private repos
                  # The GH_TOKEN_FOR_CLI in env is for the `gh` CLI, not git.
                  if git clone --depth 1 "https://oauth2:$GITHUB_TOKEN@github.com/$ORG_NAME/$REPO_NAME.git" "$REPO_DIR" &> /dev/null; then
                      CLONE_SUCCESS=true
                      echo "Successfully cloned $REPO_NAME"
                      break
                  else
                      echo "Failed to clone $REPO_NAME. Retrying in $RETRY_DELAY seconds..."
                      sleep "$RETRY_DELAY"
                  fi
              done

              if [ "$CLONE_SUCCESS" = "true" ]; then
                  pushd "$REPO_DIR" > /dev/null
                  LICENSEE_OUTPUT=$(licensee detect --json . || true) # Use || true to prevent script exit on licensee errors
                  popd > /dev/null

                  # Check if licensee detected a license and extract its SPDX ID
                  # Using // "No license found" provides a fallback if spdx_id is null or missing
                  if echo "$LICENSEE_OUTPUT" | jq -e '.license.spdx_id' &> /dev/null; then
                      DETECTED_LICENSE=$(echo "$LICENSEE_OUTPUT" | jq -r '.license.spdx_id')
                      echo "License detected for $REPO_NAME: $DETECTED_LICENSE"
                  elif echo "$LICENSEE_OUTPUT" | jq -e '.licenses[0].spdx_id' &> /dev/null; then # Handle multiple licenses if returned differently
                      DETECTED_LICENSE=$(echo "$LICENSEE_OUTPUT" | jq -r '.licenses[0].spdx_id')
                      echo "License detected for $REPO_NAME (first of many): $DETECTED_LICENSE"
                  else
                      echo "No clear SPDX license detected for $REPO_NAME."
                  fi
              else
                  DETECTED_LICENSE="Clone Failed After $MAX_RETRIES Retries"
                  echo "Failed to clone $REPO_NAME after multiple attempts."
              fi

              # Add result to temporary JSON Lines file
              jq -n \
                --arg name "$REPO_NAME" \
                --arg license "$DETECTED_LICENSE" \
                '{ "repository name": $name, "license": $license }' >> "$TEMP_JSONL_FILE"

              # Clean up cloned repository
              rm -rf "$REPO_DIR"
          done

          echo "All repositories processed. Compiling final JSON output."
          # Convert the JSON Lines file to a single JSON array
          jq -s '.' "$TEMP_JSONL_FILE" > "$SCAN_RESULTS_FILE"

          echo "Scan complete. Results saved to $SCAN_RESULTS_FILE"
          cat "$SCAN_RESULTS_FILE"

      - name: Upload License Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: license-scan-results
          path: license_scan_results.json
          retention-days: 7
