name: Secret Scanning Report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday at midnight

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests

      - name: Generate Secret Report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python secret_scanning_report.py \
            --org ${{ github.repository_owner }} \
            --token $GH_TOKEN \
            --output secret_report.csv
            
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: secret-scanning-report
          path: secret_report.csv
