--- START OF FILE secrets-scanning-report.txt ---

name: Secret Scanning Report Generator

on:
  workflow_dispatch:
    inputs:
      include_inactive:
        description: 'Include inactive alerts in report'
        required: false
        type: boolean
        default: false
      max_workers:
        description: 'Maximum number of concurrent workers'
        required: false
        type: number
        default: 10
      log_level:
        description: 'Logging level'
        required: false
        type: choice
        options:
          - INFO
          - DEBUG
          - WARNING
          - ERROR
        default: 'INFO'
      alert_threshold:
        description: 'Number of active alerts to trigger issue creation'
        required: false
        type: number
        default: 10
  schedule:
    - cron: '0 0 * * 1'

permissions:
  security-events: read
  contents: read
  actions: write
  issues: write

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: scripts/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT

      - name: Generate Secret Report
        id: generate-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.repository_owner }}
          REPORT_FILE: "secret_report_${{ steps.timestamp.outputs.timestamp }}.csv"
        run: |
          mkdir -p reports
          python ./scripts/github_secret_scanner.py \
            --org "$ORGANIZATION" \
            --token "$GITHUB_TOKEN" \
            --output "reports/${REPORT_FILE}" \
            --log-level ${{ inputs.log_level || 'INFO' }} \
            --max-workers ${{ inputs.max_workers || 10 }} \
            --max-retries 3 \
            ${{ inputs.include_inactive && '--include-inactive' || '' }}
          echo "report_path=reports/${REPORT_FILE}" >> $GITHUB_OUTPUT

      - name: Check for No Repositories
        id: check-repos
        if: success()
        run: |
          if grep -q "__NO_REPOS__" ${{ steps.generate-report.outputs.report_path }}/../output.txt; then
            echo "No repositories found in the organization.  Exiting."
            exit 1
          fi

      - name: Upload report (conditional)
        uses: actions/upload-artifact@v4
        if: success() && steps.check-repos.outcome == 'success'
        with:
          name: secret-scanning-report-${{ steps.timestamp.outputs.timestamp }}
          path: ${{ steps.generate-report.outputs.report_path }}
          retention-days: 30
          if-no-files-found: error

      - name: Process report statistics (inline)
        id: stats
        if: success() && steps.check-repos.outcome == 'success'
        run: |
          STATS=$(grep "__STATS_START__" ${{ steps.generate-report.outputs.report_path }}/../output.txt | sed 's/__STATS_START__//' | sed 's/__STATS_END__//')
          echo "total_alerts=$(echo $STATS | cut -d',' -f1 | cut -d'=' -f2)" >> $GITHUB_OUTPUT
          echo "active_alerts=$(echo $STATS | cut -d',' -f2 | cut -d'=' -f2)" >> $GITHUB_OUTPUT
          echo "inactive_alerts=$(echo $STATS | cut -d',' -f3 | cut -d'=' -f2)" >> $GITHUB_OUTPUT  # Get inactive count
          echo "Total alerts found: $(echo $STATS | cut -d',' -f1 | cut -d'=' -f2)"
          echo "Active alerts: $(echo $STATS | cut -d',' -f2 | cut -d'=' -f2)"
          echo "Inactive alerts: $(echo $STATS | cut -d',' -f3 | cut -d'=' -f2)"  # Print inactive

      - name: Create summary issue (using github-script)
        if: success() && steps.check-repos.outcome == 'success' && steps.stats.outputs.active_alerts > inputs.alert_threshold
        uses: actions/github-script@v7
        with:
          script: |
            const stats = {
              total: '${{ steps.stats.outputs.total_alerts }}',
              active: '${{ steps.stats.outputs.active_alerts }}',
              inactive: '${{ steps.stats.outputs.inactive_alerts }}',  // Include inactive in issue
            };

            const now = new Date();
            const formattedDate = now.toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric'
            });

            const body = `
            # Secret Scanning Report Summary

            Report generated on: ${now.toISOString()}

            ## Statistics
            - Total alerts analyzed: ${stats.total}
            - Active alerts found: ${stats.active}
            - Inactive alerts found: ${stats.inactive}

            ## Details
            - Report artifact: [Download report](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
            - Workflow run: [View details](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})

            ## Configuration
            - Include inactive alerts: ${{ inputs.include_inactive || 'false' }}
            - Max workers: ${{ inputs.max_workers || '10' }}
            - Log level: ${{ inputs.log_level || 'INFO' }}
            - Alert threshold: ${{ inputs.alert_threshold || '10'}}
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: \`📊 Secret Scanning Report - \${formattedDate}\`,
              body: body,
              labels: ['secret-scanning', 'report']
            });

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const body = `
            # 🚨 Secret Scanning Report Generation Failed

            Workflow run failed at ${new Date().toISOString()}

            ## Details
            - Run ID: \`${context.runId}\`
            - Trigger: ${context.eventName}
            - Actor: @${context.actor}

            ## Links
            - [View run details](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
            - [View workflow file](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/blob/main/.github/workflows/secret-scanning-report.yml)

            Please check the workflow logs for detailed error information.
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Secret Scanning Report Generation Failed',
              body: body,
              labels: ['secret-scanning', 'failed']
            });

      - name: Clean up
        if: always()
        run: |
          if [ -d "reports" ]; then
            find reports -type f -exec shred -u {} \;
            rm -rf reports
          fi

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
